service: aws-golang

provider:
  region: ap-northeast-1
  stage: master
  name: aws
  runtime: go1.x
  environment:
    TZ: Asia/Tokyo

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/main
    events:
      - httpApi:
          path: /test
          method: get

